import type { Room, Agent, Message, RoomTemplate } from '../types/room';

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: '系统架构师',
    role: 'architect',
    avatar: '/avatars/architect.png',
    personality: '理性、严谨，关注技术可行性和资源约束',
    expertise: ['系统架构', '技术选型', '资源规划'],
    model: 'deepseek-chat',
    energy: 85,
    confidence: 78,
    stance: 'support',
    isActive: true,
    color: '#3b82f6',
  },
  {
    id: 'agent-2',
    name: '风险官',
    role: 'risk_officer',
    avatar: '/avatars/risk.png',
    personality: '谨慎、质疑，关注安全、伦理和边界条件',
    expertise: ['风险评估', '安全', '合规', '伦理'],
    model: 'deepseek-chat',
    energy: 92,
    confidence: 45,
    stance: 'oppose',
    isActive: true,
    color: '#ef4444',
  },
  {
    id: 'agent-3',
    name: '策略家',
    role: 'strategist',
    avatar: '/avatars/strategist.png',
    personality: '果断、全局视野，关注目标达成和效率',
    expertise: ['战略规划', '竞争分析', '资源优化'],
    model: 'deepseek-chat',
    energy: 76,
    confidence: 82,
    stance: 'support',
    isActive: true,
    color: '#8b5cf6',
  },
  {
    id: 'agent-4',
    name: '数据分析师',
    role: 'analyst',
    avatar: '/avatars/analyst.png',
    personality: '客观、数据驱动，用数字说话',
    expertise: ['数据分析', '量化评估', '概率计算'],
    model: 'deepseek-chat',
    energy: 68,
    confidence: 60,
    stance: 'neutral',
    isActive: true,
    color: '#10b981',
  },
  {
    id: 'agent-5',
    name: '执行者',
    role: 'executor',
    avatar: '/avatars/executor.png',
    personality: '务实、注重细节，关注落地和时间线',
    expertise: ['项目管理', '执行落地', '时间管理', '细节把控'],
    model: 'deepseek-chat',
    energy: 90,
    confidence: 72,
    stance: 'neutral',
    isActive: true,
    color: '#f59e0b',
  },
];

export const mockRooms: Room[] = [
  {
    id: 'room-1',
    name: '火星殖民计划推演',
    topic: '火星殖民计划可行性分析',
    description: '多智能体协作推演人类首次火星殖民的技术、风险和执行方案',
    status: 'running',
    templateId: 'tpl-crisis',
    agents: mockAgents,
    currentPhase: 'debate',
    currentRound: 3,
    maxRounds: 10,
    consensusScore: 65,
    createdBy: 'user-1',
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now(),
    messageCount: 47,
  },
  {
    id: 'room-2',
    name: 'AI安全危机应对',
    topic: 'AGI突破后的紧急应对策略',
    description: '模拟AGI突破后的72小时危机响应，各角色协作制定应对方案',
    status: 'preparing',
    templateId: 'tpl-crisis',
    agents: mockAgents.slice(0, 4),
    currentPhase: 'info_gathering',
    currentRound: 1,
    maxRounds: 8,
    consensusScore: 0,
    createdBy: 'user-2',
    createdAt: Date.now() - 7200000,
    updatedAt: Date.now() - 3600000,
    messageCount: 0,
  },
  {
    id: 'room-3',
    name: '技术选型：微服务vs单体',
    topic: '下一代平台架构技术选型',
    description: '团队技术路线决策：微服务架构与单体架构的优劣分析',
    status: 'completed',
    templateId: 'tpl-tech',
    agents: mockAgents.slice(0, 3),
    currentPhase: 'summary',
    currentRound: 6,
    maxRounds: 6,
    consensusScore: 82,
    createdBy: 'user-1',
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 82800000,
    messageCount: 89,
  },
];

export const mockRoomDetail: Room = mockRooms[0];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    roomId: 'room-1',
    senderId: 'system',
    senderType: 'system',
    senderName: 'System',
    content: '推演开始 — 第1轮：信息收集阶段',
    type: 'phase_change',
    phase: 'info_gathering',
    round: 1,
    timestamp: Date.now() - 3600000,
  },
  {
    id: 'msg-2',
    roomId: 'room-1',
    senderId: 'agent-1',
    senderType: 'agent',
    senderName: '系统架构师',
    senderAvatar: '/avatars/architect.png',
    senderRole: 'architect',
    content: '从技术可行性角度分析，火星殖民需要解决三大核心问题：生命维持系统、能源供应和通信链路。当前SpaceX的星舰技术可以将单趟运输成本降至$100M级别，这是可行的起点。',
    type: 'text',
    phase: 'info_gathering',
    round: 1,
    timestamp: Date.now() - 3540000,
    metadata: { confidence: 85, stance: 'support' },
  },
  {
    id: 'msg-3',
    roomId: 'room-1',
    senderId: 'agent-2',
    senderType: 'agent',
    senderName: '风险官',
    senderAvatar: '/avatars/risk.png',
    senderRole: 'risk_officer',
    content: '我必须指出几个重大风险：辐射暴露（年均剂量是地球的100倍）、微重力对健康的长期影响、以及心理隔离效应。这些风险目前没有完全可靠的应对方案。',
    type: 'text',
    phase: 'info_gathering',
    round: 1,
    timestamp: Date.now() - 3480000,
    metadata: { confidence: 92, stance: 'oppose' },
  },
  {
    id: 'msg-4',
    roomId: 'room-1',
    senderId: 'agent-3',
    senderType: 'agent',
    senderName: '策略家',
    senderAvatar: '/avatars/strategist.png',
    senderRole: 'strategist',
    content: '从战略角度，火星殖民是分散人类风险的关键一步。我建议采用"分阶段推进"策略：先建立无人基地（2年），再派遣短期驻留团队（6个月），最后建立永久定居点。',
    type: 'text',
    phase: 'opinion_expression',
    round: 2,
    timestamp: Date.now() - 3300000,
    metadata: { confidence: 78, stance: 'support' },
  },
  {
    id: 'msg-5',
    roomId: 'room-1',
    senderId: 'agent-4',
    senderType: 'agent',
    senderName: '数据分析师',
    senderAvatar: '/avatars/analyst.png',
    senderRole: 'analyst',
    content: '根据NASA公开数据，火星任务的失败概率约为15-20%。但如果采用分阶段策略，每阶段可以独立评估风险，整体成功率可以提升到75%以上。需要更多数据支撑这个结论。',
    type: 'text',
    phase: 'debate',
    round: 3,
    timestamp: Date.now() - 3000000,
    metadata: { confidence: 65, stance: 'neutral' },
  },
  {
    id: 'msg-6',
    roomId: 'room-1',
    senderId: 'user-1',
    senderType: 'user',
    senderName: 'Observer',
    content: '如果优先考虑心理风险，是否可以考虑派遣双人组而不是单人？这样可以缓解孤独感。',
    type: 'text',
    phase: 'debate',
    round: 3,
    timestamp: Date.now() - 2950000,
  },
  {
    id: 'msg-7',
    roomId: 'room-1',
    senderId: 'agent-5',
    senderType: 'agent',
    senderName: '执行者',
    senderAvatar: '/avatars/executor.png',
    senderRole: 'executor',
    content: '落地执行层面，我建议采用模块化方案：每个定居舱可独立运作，万一某个模块故障不影响整体。时间线上，第一阶段18个月准备期，第二阶段36个月建设期。',
    type: 'text',
    phase: 'debate',
    round: 3,
    timestamp: Date.now() - 2800000,
    metadata: { confidence: 70, stance: 'neutral' },
  },
  {
    id: 'msg-8',
    roomId: 'room-1',
    senderId: 'system',
    senderType: 'system',
    senderName: 'System',
    content: '第3轮辩论阶段 — 当前共识度：65%',
    type: 'consensus',
    phase: 'debate',
    round: 3,
    timestamp: Date.now() - 2700000,
  },
];

export const mockTemplates: RoomTemplate[] = [
  {
    id: 'tpl-crisis',
    name: '危机应对',
    description: '模拟紧急危机场景，多角色快速响应决策',
    topic: '危机应对推演',
    defaultAgents: ['architect', 'risk_officer', 'strategist', 'executor'],
    maxRounds: 8,
  },
  {
    id: 'tpl-tech',
    name: '技术选型',
    description: '技术路线评审，多维度分析优缺点',
    topic: '技术选型推演',
    defaultAgents: ['architect', 'analyst', 'strategist'],
    maxRounds: 6,
  },
  {
    id: 'tpl-product',
    name: '产品评审',
    description: '产品方案评审，覆盖技术、市场、风险',
    topic: '产品评审推演',
    defaultAgents: ['architect', 'strategist', 'analyst', 'executor'],
    maxRounds: 8,
  },
  {
    id: 'tpl-strategy',
    name: '战略规划',
    description: '长期战略规划，多角色贡献视角',
    topic: '战略规划推演',
    defaultAgents: ['strategist', 'architect', 'analyst', 'risk_officer', 'executor'],
    maxRounds: 10,
  },
];
